---
- name: Setup DBserver
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: install mysql server
      yum:
        name: mariadb-server
        state: present

    - name: install mysql server
      yum:
        name: MySQL-python
        state: present

    - name: start & enable mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: accounts
        state: present

    - name: Create database user with name 'admin'
      mysql_user:
        name: admin
        password: 12345
        priv: '*.*:ALL'
        state: present
