---
- name: Setup Webserver
  hosts: websrvgrp
  become: yes
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present
    - name: start & enable httpd
      service:
        name: httpd
        state: started
        enabled: yes   
    - name: Copy file with owner and permissions
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
        backup: yes

- name: Setup DBserver
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: install mysql server
      yum:
        name: mariadb-server
        state: present
    - name: start & enable mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
