---
# handlers file for post-install

- name: Start and enable NTP on Redhat
  service:
          name: ntpd
          state: started
          enabled: yes
  when: ansible_os_family == "RedHat"

- name: Start and enable NTP on Debian
  service:
          name: ntp
          state: started
          enabled: yes
  when: ansible_os_family == "Debian"
