---

- name: Understanding presedence of variables
  hosts: all
  become: yes
  #  vars:
  #        USER: playuser
  #        CMNT: variable from playbook
  tasks:
          - name: create a user
            user:
                    name: "{{USER}}"
                    comment: "{{CMNT}}"
            register: USROUT

          - debug:
                  var: USROUT.name

          - debug:
                  var: USROUT.comment
                 
