---
- name: Setup DBserver
  hosts: dbsrvgrp
  become: yes
  vars:
    #dbname: groups
    #dbuser: devops
    #dbpass: 123    
  tasks:
    - name: install mysql server
      yum:
        name: mariadb-server
        state: present

    - name: install mysql server
      yum:
        name: MySQL-python
        state: present

    - name: start & enable mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: "{{dbname}}"
        state: present

    - name: Create database user with name 'admin'
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
